package woven_bankwithlogging;

// Start of user code for imports
// End of user code

/**
 * Logger class definition.
 * Generated by the TouchCORE code generator.
 */
public class Logger {
    
    public static void log(String message) {
        System.out.println(message);
    }
}
