package woven_bankwithlogging;

import java.lang.RuntimeException;

// Start of user code for imports
// End of user code

/**
 * NotEnoughtFundsException class definition.
 * Generated by the TouchCORE code generator.
 */
public class NotEnoughtFundsException extends RuntimeException {
    
    public NotEnoughtFundsException() {
        /* TODO: No message view defined */
    }
}
